#![no_std]
extern crate alloc;

mod build_dag;
mod dag_stats;
mod parse_yaml;
mod time_unit;

use alloc::{string::String, vec, vec::Vec};
#[cfg(not(any(feature = "vfed", feature = "laxity", feature = "dagfluid")))]
use awkernel_async_lib::dag_sched::policy::federated;
#[cfg(feature = "vfed")]
use awkernel_async_lib::dag_sched::policy::vfed::{self, PackingStrategy};
use awkernel_async_lib::{
    dag::finish_create_dags,
    dag_sched::{
        graph::DagGraph,
        metrics::DagMetrics,
        policy::dag_fluid::{self, Segment},
    },
};
use awkernel_lib::delay::wait_millisec;
#[cfg(not(feature = "vfed"))]
use build_dag::build_dag;
#[cfg(feature = "vfed")]
use build_dag::build_dag_vfed;

// Generated by `build.rs` from every `dag_<N>.yaml` under `DAGS_DIR`
// (see build.rs); defines `pub(crate) static DAG_FILES: &[&str]`.
include!(concat!(env!("OUT_DIR"), "/dag_files.rs"));

/// Parse a batch of RD-Gen DAG YAML documents (one string per DAG, same
/// shape [`run`] embeds via `DAG_FILES`) into [`DagMetrics`] — the same
/// `parse_yaml` -> `compute_dag_stats` -> period/deadline-from-source/sink
/// pipeline [`build_dag`] runs internally before admission, just without
/// registering or admitting anything. Public so host-side tooling (e.g. an
/// offline acceptance-ratio sweep over a directory of RD-Gen-generated task
/// sets, outside any kernel boot) can reuse this crate's own YAML-to-metrics
/// logic instead of re-deriving critical-path computation from scratch.
pub fn dag_metrics_from_yaml(yaml_files: &[&str]) -> Result<Vec<DagMetrics>, String> {
    let dags_data =
        parse_yaml::parse_dags(yaml_files).map_err(|e| alloc::format!("failed to parse: {e}"))?;
    dags_data.iter().map(dag_metrics).collect()
}

/// Parse a batch of RD-Gen DAG YAML documents into `(DagMetrics,
/// Vec<Segment>)` pairs (DAG-Fluid's segment decomposition) -- the same pipeline as
/// [`dag_metrics_from_yaml`], plus a [`dag_fluid::decompose_segments`] call
/// per DAG. Kept as a *separate* function (not a parameter on
/// `dag_metrics_from_yaml`) so existing Federated/V-Fed-only callers don't
/// pay for segment decomposition they don't use.
pub fn dag_metrics_and_fluid_segments_from_yaml(
    yaml_files: &[&str],
) -> Result<Vec<(DagMetrics, Vec<Segment>)>, String> {
    let dags_data =
        parse_yaml::parse_dags(yaml_files).map_err(|e| alloc::format!("failed to parse: {e}"))?;
    dags_data
        .iter()
        .map(|dag_data| {
            Ok((
                dag_metrics(dag_data)?,
                dag_fluid::decompose_segments(&dag_graph(dag_data)?),
            ))
        })
        .collect()
}

/// Parse a batch of RD-Gen DAG YAML documents into each DAG's precedence
/// structure ([`DagGraph`]), in input order -- what Federated's
/// list-scheduling `MINPROCS` (Baruah, DATE/IPDPS 2015) needs on top of
/// [`DagMetrics`]. See [`dag_graph`] for the node order used.
pub fn dag_graphs_from_yaml(yaml_files: &[&str]) -> Result<Vec<DagGraph>, String> {
    let dags_data =
        parse_yaml::parse_dags(yaml_files).map_err(|e| alloc::format!("failed to parse: {e}"))?;
    dags_data.iter().map(dag_graph).collect()
}

/// One DAG's [`DagMetrics`]: volume and critical path from
/// `compute_dag_stats`, period from its source node, relative deadline
/// from its sink node's `end_to_end_deadline`.
fn dag_metrics(dag_data: &parse_yaml::DagData) -> Result<DagMetrics, String> {
    let stats = dag_stats::compute_dag_stats(dag_data);
    let period = dag_data
        .get_nodes()
        .iter()
        .find(|node| node.is_source())
        .and_then(parse_yaml::NodeData::get_period)
        .ok_or_else(|| String::from("DAG has no source node with a period"))?;
    let relative_deadline = dag_data
        .get_nodes()
        .iter()
        .find(|node| node.is_sink())
        .and_then(parse_yaml::NodeData::get_end_to_end_deadline)
        .ok_or_else(|| String::from("DAG has no sink node with an end_to_end_deadline"))?;
    Ok(DagMetrics::from_static(
        stats.volume,
        stats.critical_path,
        period,
        relative_deadline,
    ))
}

/// `dag_data`'s node ids in ascending order: [`DagGraph`] index `v` of
/// [`dag_graph`]'s output is node `sorted_node_ids(dag_data)[v]`.
pub(crate) fn sorted_node_ids(dag_data: &parse_yaml::DagData) -> Vec<u32> {
    let mut ids: Vec<u32> = dag_data.get_nodes().iter().map(|n| n.get_id()).collect();
    ids.sort_unstable();
    ids
}

/// One DAG's [`DagGraph`]: nodes in ascending node-id order (see
/// [`sorted_node_ids`]; also the list-scheduling priority list), WCET =
/// `execution_time`, one edge per `out_links` entry.
pub(crate) fn dag_graph(dag_data: &parse_yaml::DagData) -> Result<DagGraph, String> {
    let ids = sorted_node_ids(dag_data);
    let index_of = |id: u32| ids.binary_search(&id).ok();

    let mut wcet = vec![0u64; ids.len()];
    let mut edges = Vec::new();
    for node in dag_data.get_nodes() {
        let from = index_of(node.get_id()).ok_or_else(|| String::from("duplicate node id"))?;
        wcet[from] = node.get_execution_time();
        for &to_id in node.get_out_links() {
            let to =
                index_of(to_id).ok_or_else(|| alloc::format!("link to unknown node id {to_id}"))?;
            edges.push((from, to));
        }
    }
    DagGraph::new(wcet, &edges).ok_or_else(|| String::from("DAG edge out of range"))
}

/// Federated's batch admission over the whole embedded task set
/// (`federated::admit_batch`, which picks Li et al. / Baruah DATE 2015 /
/// Baruah IPDPS 2015 from the set's deadline type), one assignment per DAG
/// in `dags_data` order.
#[cfg(not(any(feature = "vfed", feature = "laxity", feature = "dagfluid")))]
fn federated_admit_batch(
    dags_data: &[parse_yaml::DagData],
) -> Result<Vec<federated::FederatedAssignment>, String> {
    let metrics: Vec<DagMetrics> = dags_data
        .iter()
        .map(dag_metrics)
        .collect::<Result<_, _>>()?;
    let graphs: Vec<DagGraph> = dags_data.iter().map(dag_graph).collect::<Result<_, _>>()?;
    let tasks: Vec<federated::FedTask<'_>> = metrics
        .iter()
        .zip(graphs.iter())
        .map(|(&metrics, graph)| federated::FedTask { metrics, graph })
        .collect();
    let (variant, assignments) =
        federated::admit_batch(&tasks).map_err(|e| alloc::format!("{e}"))?;
    log::info!(
        "federated batch admission: {variant:?}, {} DAGs admitted",
        assignments.len()
    );
    Ok(assignments)
}

#[cfg(not(feature = "vfed"))]
pub async fn run() {
    wait_millisec(1000);

    // Calibrating simulated_execution_time's busy-work loop is deliberately
    // disabled for now (by user request): RD-Gen-driven DAGs should be
    // considered without accounting for their real busy-work cost. Leaving
    // this call out keeps `time_unit::ITERS_PER_MS` at its default 0, which
    // makes `busy_work_for_millisec` fall back to the old PAUSE-based
    // `wait_millisec` (see time_unit.rs's own doc) instead of doing genuine
    // CPU-bound work -- re-add the call below to switch back.
    // time_unit::calibrate_busy_work();

    // DAG-Fluid Phase 2 (see `awkernel_async_lib::dag_sched::dp_partition`'s
    // own module doc): install the DP-boundary callback before any DAG is
    // admitted, so every segment `build_dag`'s `dagfluid` arm registers
    // below has somewhere to land. A no-op for federated/laxity.
    #[cfg(feature = "dagfluid")]
    {
        awkernel_async_lib::dag_sched::dp_partition::install();
        // The background task that actually checks completion gates and
        // advances segments (see that module's own "Split design" doc --
        // this must run from ordinary task context, never from the
        // DpBoundary timer callback `install()` just registered).
        awkernel_async_lib::dag_sched::dp_partition::spawn_advancer();
    }

    let dags_data = match parse_yaml::parse_dags(DAG_FILES) {
        Ok(data) => data,
        Err(e) => {
            log::error!("Failed to parse YAML: {e}");
            return;
        }
    };

    // Federated decides the whole task set at once (see
    // `federated_admit_batch`); a rejected batch runs nothing, like the
    // papers' `return FAILURE` (and like V-Fed's `admit_batch` below).
    #[cfg(not(any(feature = "laxity", feature = "dagfluid")))]
    let federated_assignments: Vec<Option<_>> = match federated_admit_batch(&dags_data) {
        Ok(a) => a.into_iter().map(Some).collect(),
        Err(e) => {
            log::error!("federated::admit_batch rejected the whole batch: {e}");
            return;
        }
    };
    #[cfg(any(feature = "laxity", feature = "dagfluid"))]
    let federated_assignments = vec![None; dags_data.len()];

    let mut success_build_dags = vec![];

    for (dag_data, federated_assignment) in dags_data.into_iter().zip(federated_assignments) {
        match build_dag(dag_data, federated_assignment).await {
            Ok(dag) => {
                success_build_dags.push(dag);
            }
            Err(e) => {
                log::error!("Failed to build DAG: {e}");
            }
        }
    }

    if success_build_dags.is_empty() {
        log::error!("Failed to build DAG");
        return;
    }

    // Every DAG-Fluid segment across every admitted DAG is registered by
    // now (admission is sequential and complete at this point): grant each
    // DAG's own segment-0 entitlement before dispatch starts, then arm the
    // timer for the earliest boundary.
    #[cfg(feature = "dagfluid")]
    {
        awkernel_async_lib::dag_sched::dp_partition::apply_initial_entitlement();
        awkernel_async_lib::dag_sched::dp_partition::arm_next();
    }

    match finish_create_dags(&success_build_dags).await {
        Ok(_) => {
            log::info!("DAGs created successfully.");
        }
        Err(errors) => {
            log::error!("Failed to create DAGs");
            for error in errors {
                log::error!("- {error}");
            }
        }
    }
}

/// V-Fed's counterpart to the `run()` above: admits the *entire* embedded
/// task set as one batch (`vfed::admit_batch`) instead of one DAG at a time
/// in `DAG_FILES`' file order. Federated/Laxity's per-DAG loop is correct
/// for them (their admission math genuinely is per-DAG), but V-Fed's
/// Algorithm 1 sorts and packs the whole batch together -- see
/// `dag_sched::policy::vfed`'s module doc -- so reusing that loop here
/// would silently diverge from the paper's own admission decision (already
/// happening before this function existed: `vfed::admit_one` called once
/// per DAG, in file order, is a *different*, more pessimistic algorithm
/// than a real batch run).
#[cfg(feature = "vfed")]
pub async fn run() {
    wait_millisec(1000);

    // Calibrating simulated_execution_time's busy-work loop is deliberately
    // disabled for now (by user request): RD-Gen-driven DAGs should be
    // considered without accounting for their real busy-work cost. Leaving
    // this call out keeps `time_unit::ITERS_PER_MS` at its default 0, which
    // makes `busy_work_for_millisec` fall back to the old PAUSE-based
    // `wait_millisec` (see time_unit.rs's own doc) instead of doing genuine
    // CPU-bound work -- re-add the call below to switch back.
    // time_unit::calibrate_busy_work();

    // Pass 1: every DAG's `DagMetrics`, computed up front -- reparses
    // `DAG_FILES` independently of the `parse_yaml::parse_dags` call below
    // (this crate is `no_std`/boots once, so the extra parse costs nothing
    // that matters) rather than threading metrics out of a shared
    // `Vec<DagData>`, so this function stays a thin, obviously-correct
    // composition of two already-tested pieces (`dag_metrics_from_yaml`,
    // `parse_yaml::parse_dags`) instead of a new extraction path of its own.
    let configs = match dag_metrics_from_yaml(DAG_FILES) {
        Ok(c) => c,
        Err(e) => {
            log::error!("Failed to compute DAG metrics: {e}");
            return;
        }
    };

    let assignments = match vfed::admit_batch(&configs, PackingStrategy::BestFit) {
        Ok(a) => a,
        Err(e) => {
            log::error!("vfed::admit_batch rejected the whole batch: {e:?}");
            return;
        }
    };

    let dags_data = match parse_yaml::parse_dags(DAG_FILES) {
        Ok(data) => data,
        Err(e) => {
            log::error!("Failed to parse YAML: {e}");
            return;
        }
    };

    let mut success_build_dags = vec![];

    // `admit_batch` returns one `VFedAssignment` per input config, in
    // `configs`' original order (its own doc) -- the same `DAG_FILES` order
    // `dags_data` is in, since both came from independent, deterministic
    // parses of the same input, so this zip lines each DAG up with its own
    // decision.
    for (dag_data, assignment) in dags_data.into_iter().zip(assignments) {
        match build_dag_vfed(dag_data, assignment).await {
            Ok(dag) => {
                success_build_dags.push(dag);
            }
            Err(e) => {
                log::error!("Failed to build DAG: {e}");
            }
        }
    }

    if success_build_dags.is_empty() {
        log::error!("Failed to build DAG");
        return;
    }

    match finish_create_dags(&success_build_dags).await {
        Ok(_) => {
            log::info!("DAGs created successfully.");
        }
        Err(errors) => {
            log::error!("Failed to create DAGs");
            for error in errors {
                log::error!("- {error}");
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use awkernel_async_lib::dag_sched::policy::federated::list_schedule_makespan;

    /// Diamond 0 -> {1, 2} -> 3 with WCETs 10, 30, 5, 5 (node ids given out
    /// of order in the YAML): the graph must follow the links, not the file
    /// order.
    #[test]
    fn test_dag_graphs_from_yaml_diamond() {
        let dag_file = "links:
  - source: 0
    target: 1
  - source: 0
    target: 2
  - source: 1
    target: 3
  - source: 2
    target: 3
nodes:
  - end_to_end_deadline: 100
    execution_time: 5
    id: 3
  - execution_time: 10
    id: 0
    period: 50
  - execution_time: 30
    id: 1
  - execution_time: 5
    id: 2
";
        let graphs = dag_graphs_from_yaml(&[dag_file]).unwrap();
        assert_eq!(graphs[0].len(), 4);
        assert_eq!(list_schedule_makespan(&graphs[0], 1), Some(50)); // volume
        assert_eq!(list_schedule_makespan(&graphs[0], 2), Some(45)); // critical path
    }
}
