#![no_std]
extern crate alloc;

mod build_dag;
pub mod dag_fluid;
mod dag_stats;
mod parse_yaml;
mod time_unit;

use alloc::{string::String, vec, vec::Vec};
use awkernel_async_lib::{dag::finish_create_dags, dag_sched::metrics::DagMetrics};
use awkernel_lib::delay::wait_millisec;
#[cfg(not(feature = "vfed"))]
use build_dag::build_dag;
#[cfg(feature = "vfed")]
use build_dag::build_dag_vfed;
#[cfg(feature = "vfed")]
use awkernel_async_lib::dag_sched::policy::vfed::{self, PackingStrategy};

// Generated by `build.rs` from every `dag_<N>.yaml` under `DAGS_DIR`
// (see build.rs); defines `pub(crate) static DAG_FILES: &[&str]`.
include!(concat!(env!("OUT_DIR"), "/dag_files.rs"));

/// Parse a batch of RD-Gen DAG YAML documents (one string per DAG, same
/// shape [`run`] embeds via `DAG_FILES`) into [`DagMetrics`] — the same
/// `parse_yaml` -> `compute_dag_stats` -> period/deadline-from-source/sink
/// pipeline [`build_dag`] runs internally before admission, just without
/// registering or admitting anything. Public so host-side tooling (e.g. an
/// offline acceptance-ratio sweep over a directory of RD-Gen-generated task
/// sets, outside any kernel boot) can reuse this crate's own YAML-to-metrics
/// logic instead of re-deriving critical-path computation from scratch.
pub fn dag_metrics_from_yaml(yaml_files: &[&str]) -> Result<Vec<DagMetrics>, String> {
    let dags_data =
        parse_yaml::parse_dags(yaml_files).map_err(|e| alloc::format!("failed to parse: {e}"))?;

    dags_data
        .iter()
        .map(|dag_data| {
            let stats = dag_stats::compute_dag_stats(dag_data);
            let period = dag_data
                .get_nodes()
                .iter()
                .find(|node| node.is_source())
                .and_then(parse_yaml::NodeData::get_period)
                .ok_or_else(|| String::from("DAG has no source node with a period"))?;
            let relative_deadline = dag_data
                .get_nodes()
                .iter()
                .find(|node| node.is_sink())
                .and_then(parse_yaml::NodeData::get_end_to_end_deadline)
                .ok_or_else(|| {
                    String::from("DAG has no sink node with an end_to_end_deadline")
                })?;
            Ok(DagMetrics::from_static(
                stats.volume,
                stats.critical_path,
                period,
                relative_deadline,
            ))
        })
        .collect()
}

/// Parse a batch of RD-Gen DAG YAML documents into `(DagMetrics,
/// Vec<dag_fluid::Segment>)` pairs -- the same pipeline as
/// [`dag_metrics_from_yaml`], plus a [`dag_fluid::decompose_segments`] call
/// per DAG. Kept as a *separate* function (not a parameter on
/// `dag_metrics_from_yaml`) so existing Federated/V-Fed-only callers don't
/// pay for segment decomposition they don't use.
pub fn dag_metrics_and_fluid_segments_from_yaml(
    yaml_files: &[&str],
) -> Result<Vec<(DagMetrics, Vec<dag_fluid::Segment>)>, String> {
    let dags_data =
        parse_yaml::parse_dags(yaml_files).map_err(|e| alloc::format!("failed to parse: {e}"))?;

    dags_data
        .iter()
        .map(|dag_data| {
            let stats = dag_stats::compute_dag_stats(dag_data);
            let period = dag_data
                .get_nodes()
                .iter()
                .find(|node| node.is_source())
                .and_then(parse_yaml::NodeData::get_period)
                .ok_or_else(|| String::from("DAG has no source node with a period"))?;
            let relative_deadline = dag_data
                .get_nodes()
                .iter()
                .find(|node| node.is_sink())
                .and_then(parse_yaml::NodeData::get_end_to_end_deadline)
                .ok_or_else(|| {
                    String::from("DAG has no sink node with an end_to_end_deadline")
                })?;
            let metrics = DagMetrics::from_static(
                stats.volume,
                stats.critical_path,
                period,
                relative_deadline,
            );
            let segments = dag_fluid::decompose_segments(dag_data);
            Ok((metrics, segments))
        })
        .collect()
}

#[cfg(not(feature = "vfed"))]
pub async fn run() {
    wait_millisec(1000);

    let dags_data = match parse_yaml::parse_dags(DAG_FILES) {
        Ok(data) => data,
        Err(e) => {
            log::error!("Failed to parse YAML: {e}");
            return;
        }
    };

    let mut success_build_dags = vec![];

    for dag_data in dags_data {
        match build_dag(dag_data).await {
            Ok(dag) => {
                success_build_dags.push(dag);
            }
            Err(e) => {
                log::error!("Failed to build DAG: {e}");
            }
        }
    }

    if success_build_dags.is_empty() {
        log::error!("Failed to build DAG");
        return;
    }

    match finish_create_dags(&success_build_dags).await {
        Ok(_) => {
            log::info!("DAGs created successfully.");
        }
        Err(errors) => {
            log::error!("Failed to create DAGs");
            for error in errors {
                log::error!("- {error}");
            }
        }
    }
}

/// V-Fed's counterpart to the `run()` above: admits the *entire* embedded
/// task set as one batch (`vfed::admit_batch`) instead of one DAG at a time
/// in `DAG_FILES`' file order. Federated/Laxity's per-DAG loop is correct
/// for them (their admission math genuinely is per-DAG), but V-Fed's
/// Algorithm 1 sorts and packs the whole batch together -- see
/// `dag_sched::policy::vfed`'s module doc -- so reusing that loop here
/// would silently diverge from the paper's own admission decision (already
/// happening before this function existed: `vfed::admit_one` called once
/// per DAG, in file order, is a *different*, more pessimistic algorithm
/// than a real batch run).
#[cfg(feature = "vfed")]
pub async fn run() {
    wait_millisec(1000);

    // Pass 1: every DAG's `DagMetrics`, computed up front -- reparses
    // `DAG_FILES` independently of the `parse_yaml::parse_dags` call below
    // (this crate is `no_std`/boots once, so the extra parse costs nothing
    // that matters) rather than threading metrics out of a shared
    // `Vec<DagData>`, so this function stays a thin, obviously-correct
    // composition of two already-tested pieces (`dag_metrics_from_yaml`,
    // `parse_yaml::parse_dags`) instead of a new extraction path of its own.
    let configs = match dag_metrics_from_yaml(DAG_FILES) {
        Ok(c) => c,
        Err(e) => {
            log::error!("Failed to compute DAG metrics: {e}");
            return;
        }
    };

    let assignments = match vfed::admit_batch(&configs, PackingStrategy::FirstFit) {
        Ok(a) => a,
        Err(e) => {
            log::error!("vfed::admit_batch rejected the whole batch: {e:?}");
            return;
        }
    };

    let dags_data = match parse_yaml::parse_dags(DAG_FILES) {
        Ok(data) => data,
        Err(e) => {
            log::error!("Failed to parse YAML: {e}");
            return;
        }
    };

    let mut success_build_dags = vec![];

    // `admit_batch` returns one `VFedAssignment` per input config, in
    // `configs`' original order (its own doc) -- the same `DAG_FILES` order
    // `dags_data` is in, since both came from independent, deterministic
    // parses of the same input, so this zip lines each DAG up with its own
    // decision.
    for (dag_data, assignment) in dags_data.into_iter().zip(assignments) {
        match build_dag_vfed(dag_data, assignment).await {
            Ok(dag) => {
                success_build_dags.push(dag);
            }
            Err(e) => {
                log::error!("Failed to build DAG: {e}");
            }
        }
    }

    if success_build_dags.is_empty() {
        log::error!("Failed to build DAG");
        return;
    }

    match finish_create_dags(&success_build_dags).await {
        Ok(_) => {
            log::info!("DAGs created successfully.");
        }
        Err(errors) => {
            log::error!("Failed to create DAGs");
            for error in errors {
                log::error!("- {error}");
            }
        }
    }
}
