//! Generates `$OUT_DIR/dag_files.rs`, a `DAG_FILES: &[&str]` constant with one
//! `include_str!` entry per `dag_<N>.yaml` found under [`DAGS_DIR`], instead
//! of requiring one hand-written `include_str!` constant per file in
//! `lib.rs`. Runs on the host with `std` regardless of the crate's own
//! `#![no_std]` (Cargo always builds `build.rs` as a normal host binary).

use std::{
    env, fs,
    path::{Path, PathBuf},
};

/// Folder to load every `dag_<N>.yaml` file from (searched recursively).
/// Point this at a different RD-Gen output directory to change the DAG set
/// the kernel spawns.
const DAGS_DIR: &str = "/home/nokosan/azumi-lab/RD-Gen/test/TU=3/DAGs";

/// True for `dag_<N>.yaml`/`.yml` files. RD-Gen writes sibling files in the
/// same directory that are not DAG definitions (e.g. `combination_log.yaml`,
/// `dag_<N>.png`/`.eps` renders); `parse_yaml::parse_dags` fails the entire
/// batch on the first file that isn't a single-document DAG YAML, so those
/// must be filtered out here rather than left for it to reject at runtime.
fn is_dag_yaml(path: &Path) -> bool {
    let is_yaml = path
        .extension()
        .is_some_and(|ext| ext == "yaml" || ext == "yml");
    let is_dag_named = path
        .file_name()
        .and_then(|name| name.to_str())
        .is_some_and(|name| name.starts_with("dag_"));
    is_yaml && is_dag_named
}

/// The `<N>` in `dag_<N>.yaml`, used to sort files in the natural order
/// RD-Gen generates them in (0, 1, 2, ..., 10, ...) rather than the
/// lexicographic order their filenames sort in (0, 1, 10, 11, ..., 2, ...).
/// Falls back to `usize::MAX` (sorted last) for a name that doesn't fit the
/// pattern, rather than failing the build over a cosmetic ordering detail.
fn dag_index(path: &Path) -> usize {
    path.file_stem()
        .and_then(|stem| stem.to_str())
        .and_then(|stem| stem.strip_prefix("dag_"))
        .and_then(|n| n.parse().ok())
        .unwrap_or(usize::MAX)
}

fn collect_dag_yaml_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_dag_yaml_files(&path, out);
        } else if is_dag_yaml(&path) {
            out.push(path);
        }
    }
}

fn main() {
    println!("cargo:rerun-if-changed={DAGS_DIR}");

    let mut files = Vec::new();
    collect_dag_yaml_files(Path::new(DAGS_DIR), &mut files);
    files.sort_by_key(|path| dag_index(path));

    assert!(
        !files.is_empty(),
        "no dag_<N>.yaml files found under DAGS_DIR ({DAGS_DIR})"
    );

    let mut generated = String::from(
        "// Auto-generated by build.rs from DAGS_DIR -- do not edit by hand.\n\
         pub(crate) static DAG_FILES: &[&str] = &[\n",
    );
    for file in &files {
        println!("cargo:rerun-if-changed={}", file.display());
        // A trailing newline is required by the yaml_peg specification.
        generated.push_str(&format!(
            "    concat!(include_str!({file:?}), \"\\n\"),\n"
        ));
    }
    generated.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set by cargo");
    fs::write(Path::new(&out_dir).join("dag_files.rs"), generated)
        .expect("failed to write generated dag_files.rs");
}
