//! Acceptance-ratio comparison of V-Fed and the federated algorithms under
//! the TPDS 2023 V-Fed paper's own evaluation setup (Sec. 7), on a pool of
//! DAG structures generated by `scripts/melani_dag_generator.py` (a port of
//! the paper's generator [21]).
//!
//! Two ways to tie the processor count `m` to `U_norm`, per trial, with
//! `N = 8` DAGs drawn (distinct) from the pool either way:
//!
//! **Per-trial `m` (default; the V-Fed paper's own method, Sec. 7)**
//! - `D_i` uniform integer in `[L_i, L_i / α]` (`α = 0.3` by default);
//! - `T_i = D_i` (`implicit`, Fig. 8) or `T_i = D_i / β` with
//!   `β ~ Uniform[0.1, 1]` (`constrained`, Fig. 9);
//! - `m = ceil(U_Σ / U_norm)`. With this generator's DAGs (`C/L` ~ 12) that
//!   typically means m in the tens to hundreds of cores.
//!
//! **Fixed `m` (`--cores M`; the method of Guan et al., TC 2022, Sec. 7.1,
//! and the Verucchi et al. 2023 survey)**
//! - target `U_Σ = U_norm · M`, split over the N DAGs by UUniFast-Discard
//!   (Davis & Burns) with per-DAG cap `U_i <= C_i / L_i` -- the cap Guan et
//!   al. derive for constrained deadlines, `U_i <= C_i · max(D/T) / L_i`
//!   with `max(D/T) = 1`. (Guan et al. use Dirichlet-Rescale; both sample
//!   uniformly from the same capped simplex.) A draw whose caps sum below
//!   the target is redrawn, like Guan et al.'s "generate DAG structures
//!   until the utilization upper bounds exceed U";
//! - `T_i = ceil(C_i / U_i)`; `D_i = T_i` (`implicit`) or `D_i` uniform
//!   integer in `[L_i, T_i]` (`constrained`); `α` is unused.
//!
//! Either way, OURS2's maximum parallelism `L_i` is a uniform integer in
//! `[m_i/2, m_i]` (`m_i = ceil((C_i - L_i)/(D_i - L_i))`), as in the V-Fed
//! paper; OURS1 leaves it unknown.
//!
//! Columns: `li` = federated per Li et al. (`FederatedVariant::LiImplicit`;
//! defined for implicit deadlines only, so printed as `-` in
//! `constrained` mode),
//! `date` = Baruah DATE 2015 (`FederatedVariant::BaruahConstrained`
//! forced; valid for implicit deadlines too, as a special case), `ours1` /
//! `ours2` = V-Fed, `fluid` = DAG-Fluid (Guan et al., TC 2022), `sfs` =
//! SFS-G (Lendve et al., JSA 2026; `policy::sfs`). The pool's
//! mean parallelism `C/L` is printed to stderr, so pools generated with
//! different generator parameters can be compared on that axis.
//!
//! Usage: `paper_setting_comparison <pool_dir> <implicit|constrained>
//! <u_norm_min> <u_norm_max> <u_norm_step> <trials> [alpha] [--cores M]`

use std::{env, fs, path::Path, process::ExitCode};

use awkernel_async_lib::dag_sched::{
    metrics::DagMetrics,
    policy::{
        federated::{self, DagGraph, FedTask, FederatedVariant},
        sfs::{self, SfsTask},
        vfed::{self, PackingStrategy},
    },
};
use rand::{Rng, seq::IndexedRandom};
use rd_gen_to_dags::dag_fluid::{self, Segment};

const DAGS_PER_SET: usize = 8;

struct Structure {
    volume: u64,
    critical_path: u64,
    graph: DagGraph,
    segments: Vec<Segment>,
}

fn main() -> ExitCode {
    let mut args: Vec<String> = env::args().collect();
    let fixed_cores: Option<u16> = match args.iter().position(|a| a == "--cores") {
        None => None,
        Some(i) => {
            let value = args
                .get(i + 1)
                .and_then(|v| v.parse::<u16>().ok())
                .filter(|m| *m > 0);
            let Some(m) = value else {
                eprintln!("--cores needs a positive integer");
                return ExitCode::from(2);
            };
            args.drain(i..=i + 1);
            Some(m)
        }
    };
    let (pool_dir, mode, lo, hi, step, trials, alpha) = match args.as_slice() {
        [_, p, m, lo, hi, st, t] => (p, m, lo, hi, st, t, None),
        [_, p, m, lo, hi, st, t, a] => (p, m, lo, hi, st, t, Some(a)),
        _ => {
            eprintln!(
                "usage: paper_setting_comparison <pool_dir> <implicit|constrained> \
                 <u_norm_min> <u_norm_max> <u_norm_step> <trials> [alpha] [--cores M]"
            );
            return ExitCode::from(2);
        }
    };
    let implicit = match mode.as_str() {
        "implicit" => true,
        "constrained" => false,
        other => {
            eprintln!("deadline mode must be 'implicit' or 'constrained', got '{other}'");
            return ExitCode::from(2);
        }
    };
    let parse = |s: &str| s.parse::<f64>().ok().filter(|v| *v > 0.0);
    let (Some(lo), Some(hi), Some(step)) = (parse(lo), parse(hi), parse(step)) else {
        eprintln!("u_norm_min/max/step must be positive numbers");
        return ExitCode::from(2);
    };
    let Some(trials) = trials.parse::<usize>().ok().filter(|t| *t > 0) else {
        eprintln!("trials must be a positive integer");
        return ExitCode::from(2);
    };
    let alpha = match alpha.map(|a| parse(a)) {
        None => 0.3,
        Some(Some(a)) if a <= 1.0 => a,
        Some(_) => {
            eprintln!("alpha must be in (0, 1]");
            return ExitCode::from(2);
        }
    };

    let pool = match load_pool(Path::new(pool_dir)) {
        Ok(p) if p.len() >= DAGS_PER_SET => p,
        Ok(p) => {
            eprintln!("pool has only {} DAGs (< {DAGS_PER_SET})", p.len());
            return ExitCode::FAILURE;
        }
        Err(e) => {
            eprintln!("{e}");
            return ExitCode::FAILURE;
        }
    };
    let mean_parallelism = pool
        .iter()
        .map(|s| s.volume as f64 / s.critical_path as f64)
        .sum::<f64>()
        / pool.len() as f64;
    let m_desc = match fixed_cores {
        Some(m) => format!("fixed m={m}"),
        None => format!("per-trial m, alpha={alpha}"),
    };
    eprintln!(
        "pool: {} DAG structures, mean C/L = {mean_parallelism:.2}, mode={mode}, {m_desc}",
        pool.len()
    );

    let mut rng = rand::rng();
    println!("u_norm,li,date,ours1,ours2,fluid,sfs");
    let n_steps = ((hi - lo) / step + 1e-9).floor() as usize;
    for k in 0..=n_steps {
        let u_norm = ((lo + k as f64 * step) * 1e4).round() / 1e4;
        let (mut li, mut date, mut ours1, mut ours2, mut fluid) =
            (0usize, 0usize, 0usize, 0usize, 0usize);
        let mut sfs_ok = 0usize;
        let mut redraws = 0usize;
        for _ in 0..trials {
            let (drawn, metrics, m) = match fixed_cores {
                None => {
                    let drawn: Vec<&Structure> =
                        pool.choose_multiple(&mut rng, DAGS_PER_SET).collect();
                    let metrics = per_trial_m_timing(&drawn, alpha, implicit, &mut rng);
                    let u_sigma: f64 = metrics
                        .iter()
                        .map(|c| c.volume as f64 / c.period as f64)
                        .sum();
                    (drawn, metrics, ((u_sigma / u_norm).ceil() as u16).max(1))
                }
                Some(m) => {
                    let target = u_norm * m as f64;
                    let mut attempt = 0usize;
                    loop {
                        let drawn: Vec<&Structure> =
                            pool.choose_multiple(&mut rng, DAGS_PER_SET).collect();
                        if let Some(metrics) = fixed_m_timing(&drawn, target, implicit, &mut rng) {
                            break (drawn, metrics, m);
                        }
                        attempt += 1;
                        redraws += 1;
                        if attempt >= MAX_REDRAWS {
                            eprintln!(
                                "u_norm={u_norm}: no draw reaches U_sigma={target:.2} within \
                                 {MAX_REDRAWS} redraws (sum of C/L caps too small for this pool); \
                                 stopping"
                            );
                            return ExitCode::FAILURE;
                        }
                    }
                }
            };

            let tasks: Vec<FedTask<'_>> = drawn
                .iter()
                .zip(metrics.iter())
                .map(|(s, &metrics)| FedTask {
                    metrics,
                    graph: &s.graph,
                })
                .collect();
            if implicit {
                li +=
                    federated::plan_batch(&tasks, m, FederatedVariant::LiImplicit).is_ok() as usize;
            }
            date += federated::plan_batch(&tasks, m, FederatedVariant::BaruahConstrained).is_ok()
                as usize;
            ours1 += vfed::is_batch_feasible(&metrics, m, PackingStrategy::BestFit) as usize;

            let with_parallelism: Vec<DagMetrics> = metrics
                .iter()
                .map(|c| match c.min_dedicated_cores() {
                    Some(mi) => {
                        let lo = mi.div_ceil(2);
                        let max_parallelism = if lo >= mi {
                            mi
                        } else {
                            rng.random_range(lo..=mi)
                        };
                        DagMetrics {
                            max_parallelism,
                            ..*c
                        }
                    }
                    None => *c,
                })
                .collect();
            ours2 +=
                vfed::is_batch_feasible(&with_parallelism, m, PackingStrategy::BestFit) as usize;

            let fluid_entries: Vec<(u64, u64, u64, u64, &[Segment])> = drawn
                .iter()
                .zip(metrics.iter())
                .map(|(s, c)| {
                    (
                        c.volume,
                        c.period,
                        c.critical_path,
                        c.relative_deadline,
                        s.segments.as_slice(),
                    )
                })
                .collect();
            fluid += dag_fluid::is_batch_feasible(&fluid_entries, m) as usize;

            let sfs_tasks: Vec<SfsTask<'_>> = drawn
                .iter()
                .zip(metrics.iter())
                .map(|(s, c)| SfsTask {
                    graph: &s.graph,
                    period: c.period,
                    deadline: c.relative_deadline,
                })
                .collect();
            sfs_ok += sfs::is_schedulable(&sfs_tasks, m) as usize;
        }
        if redraws > 0 {
            eprintln!("u_norm={u_norm}: {redraws} structure redraws (caps below target)");
        }
        let pct = |x: usize| 100.0 * x as f64 / trials as f64;
        let li_col = if implicit {
            alloc_fmt(pct(li))
        } else {
            String::from("-")
        };
        println!(
            "{u_norm:.4},{li_col},{:.2},{:.2},{:.2},{:.2},{:.2}",
            pct(date),
            pct(ours1),
            pct(ours2),
            pct(fluid),
            pct(sfs_ok)
        );
    }
    ExitCode::SUCCESS
}

/// Structure redraws allowed per trial in fixed-`m` mode before giving up.
const MAX_REDRAWS: usize = 10_000;
/// UUniFast-Discard attempts per structure draw before redrawing structures.
const MAX_UUNIFAST_TRIES: usize = 1_000;

/// The V-Fed paper's timing: `D ~ U[L, L/α]`, `T = D` or `D/β`.
fn per_trial_m_timing(
    drawn: &[&Structure],
    alpha: f64,
    implicit: bool,
    rng: &mut impl Rng,
) -> Vec<DagMetrics> {
    drawn
        .iter()
        .map(|s| {
            let l = s.critical_path;
            let d_max = ((l as f64 / alpha).floor() as u64).max(l);
            let d = rng.random_range(l..=d_max);
            let t = if implicit {
                d
            } else {
                let beta: f64 = rng.random_range(0.1..=1.0);
                ((d as f64 / beta).floor() as u64).max(d)
            };
            DagMetrics::from_static(s.volume, l, t, d)
        })
        .collect()
}

/// Guan et al.'s fixed-`m` timing (see the module doc), or `None` if this
/// draw cannot reach `target` (caps too small, or UUniFast-Discard keeps
/// failing) and the structures should be redrawn.
fn fixed_m_timing(
    drawn: &[&Structure],
    target: f64,
    implicit: bool,
    rng: &mut impl Rng,
) -> Option<Vec<DagMetrics>> {
    let caps: Vec<f64> = drawn
        .iter()
        .map(|s| s.volume as f64 / s.critical_path as f64)
        .collect();
    if caps.iter().sum::<f64>() < target {
        return None;
    }
    let n = drawn.len();
    let utils = (0..MAX_UUNIFAST_TRIES).find_map(|_| {
        // UUniFast (Bini & Buttazzo) over n tasks summing to `target`,
        // discarded unless every share is within its cap.
        let mut sum = target;
        let mut u = Vec::with_capacity(n);
        for i in 0..n - 1 {
            let r: f64 = rng.random_range(0.0..1.0);
            let next = sum * r.powf(1.0 / (n - i - 1) as f64);
            u.push(sum - next);
            sum = next;
        }
        u.push(sum);
        u.iter()
            .zip(&caps)
            .all(|(ui, cap)| *ui > 0.0 && ui <= cap)
            .then_some(u)
    })?;
    Some(
        drawn
            .iter()
            .zip(utils)
            .map(|(s, ui)| {
                let l = s.critical_path;
                // ceil keeps U_i <= its cap, hence T >= L.
                let t = ((s.volume as f64 / ui).ceil() as u64).max(l);
                let d = if implicit { t } else { rng.random_range(l..=t) };
                DagMetrics::from_static(s.volume, l, t, d)
            })
            .collect(),
    )
}

fn alloc_fmt(x: f64) -> String {
    format!("{x:.2}")
}

fn load_pool(dir: &Path) -> Result<Vec<Structure>, String> {
    let mut paths: Vec<_> = fs::read_dir(dir)
        .map_err(|e| format!("cannot read directory '{}': {e}", dir.display()))?
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|x| x == "yaml"))
        .filter(|p| {
            p.file_stem()
                .and_then(|s| s.to_str())
                .is_some_and(|s| s.starts_with("dag_"))
        })
        .collect();
    paths.sort();
    let texts: Vec<String> = paths
        .iter()
        .map(|p| fs::read_to_string(p).map_err(|e| format!("cannot read {}: {e}", p.display())))
        .collect::<Result<_, _>>()?;
    let refs: Vec<&str> = texts.iter().map(String::as_str).collect();
    let with_segments = rd_gen_to_dags::dag_metrics_and_fluid_segments_from_yaml(&refs)?;
    let graphs = rd_gen_to_dags::dag_graphs_from_yaml(&refs)?;
    Ok(with_segments
        .into_iter()
        .zip(graphs)
        .map(|((m, segments), graph)| Structure {
            volume: m.volume,
            critical_path: m.critical_path,
            graph,
            segments,
        })
        .collect())
}
